# Generated by Django 6.0.6 on 2026-08-26 22:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_cart'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.coupon'),
        ),
        migrations.AddField(
            model_name='cart',
            name='tip_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Delivery partner tip amount in ₹', max_digits=6),
        ),
    ]
