# Generated by Django 6.0.6 on 2026-08-26 22:25

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Promo coupon code e.g. WELCOME50', max_length=20, unique=True)),
                ('description', models.CharField(help_text='Promotional summary e.g. Flat ₹50 OFF on orders above ₹199', max_length=255)),
                ('discount_type', models.CharField(choices=[('FLAT', 'Flat Amount Discount (₹)'), ('PERCENTAGE', 'Percentage Discount (%)')], default='FLAT', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Flat amount in ₹ or percentage value', max_digits=8)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum items subtotal required', max_digits=8)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount cap for percentage discounts (in ₹)', max_digits=8, null=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('usage_limit', models.PositiveIntegerField(default=1000, help_text='Maximum times this coupon can be redeemed')),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons & Offers',
                'ordering': ['-created_at'],
            },
        ),
    ]
