# Generated by Django 6.0.6 on 2026-08-26 22:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_partner_phone',
            new_name='rider_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_partner_name',
        ),
        migrations.AddField(
            model_name='order',
            name='darkstore_lat',
            field=models.FloatField(default=12.9352),
        ),
        migrations.AddField(
            model_name='order',
            name='darkstore_lng',
            field=models.FloatField(default=77.6245),
        ),
        migrations.AddField(
            model_name='order',
            name='dest_lat',
            field=models.FloatField(default=12.939),
        ),
        migrations.AddField(
            model_name='order',
            name='dest_lng',
            field=models.FloatField(default=77.629),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_name',
            field=models.CharField(default='Ramesh Kumar', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_rating',
            field=models.DecimalField(decimal_places=1, default=Decimal('4.9'), max_digits=3),
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle_number',
            field=models.CharField(default='KA-01-EQ-9872', max_length=20),
        ),
    ]
