# Generated by Django 6.0.6 on 2026-08-26 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_alter_product_category_alter_product_subcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DarkStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Unique Dark Store Identifier e.g. DS-BLR-01', max_length=20, unique=True)),
                ('address', models.TextField(help_text='Detailed physical address of micro-fulfillment center')),
                ('city', models.CharField(default='Bengaluru', max_length=50)),
                ('state', models.CharField(default='Karnataka', max_length=50)),
                ('serviceable_pincodes', models.TextField(help_text='Comma-separated serviceable pincodes e.g. 560034, 560095, 560047, 560100')),
                ('avg_delivery_mins', models.IntegerField(default=10, help_text='Average delivery turnaround in minutes')),
                ('is_active', models.BooleanField(default=True, help_text='Operational status (Open / Closed)')),
                ('latitude', models.FloatField(default=12.9352, help_text='Store latitude coordinate')),
                ('longitude', models.FloatField(default=77.6245, help_text='Store longitude coordinate')),
                ('contact_phone', models.CharField(blank=True, default='+91 9876543210', max_length=20)),
                ('manager_name', models.CharField(blank=True, default='Store Supervisor', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dark Store',
                'verbose_name_plural': 'Dark Stores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DarkStoreInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.PositiveIntegerField(default=50)),
                ('is_available', models.BooleanField(default=True, help_text='Store-level product availability switch')),
                ('low_stock_threshold', models.PositiveIntegerField(default=10, help_text='Quantity threshold for low stock alert')),
                ('last_restocked_at', models.DateTimeField(auto_now=True)),
                ('dark_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='darkstore.darkstore')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_inventories', to='products.product')),
            ],
            options={
                'verbose_name': 'Dark Store Inventory',
                'verbose_name_plural': 'Dark Store Inventories',
                'ordering': ['dark_store', 'product__name'],
                'unique_together': {('dark_store', 'product')},
            },
        ),
    ]
